// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt5Ymf-059WeM2wpXaWacwK_LTDAlIbpA',
    appId: '1:433573353285:web:aaacc79ee0e8848f7a902c',
    messagingSenderId: '433573353285',
    projectId: 'e-commerce-app-19d36',
    authDomain: 'e-commerce-app-19d36.firebaseapp.com',
    storageBucket: 'e-commerce-app-19d36.appspot.com',
    measurementId: 'G-GTG83R90FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlzMmHB_Hdowyrf5J9PjTdJ7B89wrteig',
    appId: '1:433573353285:android:a79fa5a7fedc6aba7a902c',
    messagingSenderId: '433573353285',
    projectId: 'e-commerce-app-19d36',
    storageBucket: 'e-commerce-app-19d36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBL0yJ3qZh-9O6v_yXKQGUacp2dGKJ_rY',
    appId: '1:433573353285:ios:2479217390063ebc7a902c',
    messagingSenderId: '433573353285',
    projectId: 'e-commerce-app-19d36',
    storageBucket: 'e-commerce-app-19d36.appspot.com',
    androidClientId: '433573353285-4qu1kf4ph9bh6l64nlj0bedc9mppjgig.apps.googleusercontent.com',
    iosClientId: '433573353285-673kcpe6csnnegbaci100dmspugqcan9.apps.googleusercontent.com',
    iosBundleId: 'com.bloc.basic.blocBasic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBL0yJ3qZh-9O6v_yXKQGUacp2dGKJ_rY',
    appId: '1:433573353285:ios:2479217390063ebc7a902c',
    messagingSenderId: '433573353285',
    projectId: 'e-commerce-app-19d36',
    storageBucket: 'e-commerce-app-19d36.appspot.com',
    androidClientId: '433573353285-4qu1kf4ph9bh6l64nlj0bedc9mppjgig.apps.googleusercontent.com',
    iosClientId: '433573353285-673kcpe6csnnegbaci100dmspugqcan9.apps.googleusercontent.com',
    iosBundleId: 'com.bloc.basic.blocBasic',
  );
}
